name: Deploy feature branches to nonproduction bucket by Moisa

on:
    push:
      branches:
        - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-473a3e3aee89174bb7c501d7c-nonprodbucket-s7v7kckenldo
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret.access-key: {{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up node js 
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: |
          npm ci
          npm run build
      - name: deploy files to bucket
        run: aws S3 cp public s3://{{ env.BUCKET_NAME }}/ --recursive --acl public-read
